### PR TITLE
add support for proto3 optional field presence

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by thesamet** [comment]
Thanks for submitting the PR. To ensure things work correctly, can you add a few tests under e2e to ensure rules defined on optionals work correctly? It looks like PGV 0.6.3 just got released  with the same feature (https://github.com/scalapb/scalapb-validate/commit/5a24b23c1d0617c1bdcc42d4cf8cca6d5fd55dd3) so I'll take a look after this to sync their test suite with scalapb-validate.

**Comment by aldenml** [comment]
will do that, thanks for the review

**Comment by aldenml** [comment]
Hi @thesamet , I added the test (ci seems that requires your approval).

**Comment by thesamet** [comment]
Looks like tests passed, but scalafmt failed. Please run scalafmt and submit another commit within this PR.

**Comment by aldenml** [comment]
ok, `scalafmt` it's green on my env now

**Comment by thesamet** [comment]
Thank you!

**Comment by thesamet** [comment]
When syncing pgv 6.3 test suite, I noticed that the current behaviour in scalapb-validate varies from the PGV error. I filed [this issue](https://github.com/envoyproxy/protoc-gen-validate/issues/558). I want to have this clarified before cutting a release for scalapb-validate. In the meantime, we do have snapshot releases that include this PR: https://oss.sonatype.org/content/repositories/snapshots/com/thesamet/scalapb/protoc-gen-scalapb-validate/0.3.2+47-9c19c91d-SNAPSHOT/

**Comment by aldenml** [comment]
Interesting, I looked at it now, and for me, the PGV behavior is counterintuitive. Let's see what they say. And thank you for the amazing work with scalapb.

**Pull request merged**
